// In-memory dedup — works within same instance
const processed = new Set();

export async function handler(event) {
  console.log("payment-webhook triggered");

  try {
    const params = new URLSearchParams(event.body);
    const paymentId = params.get("id");

    if (!paymentId) {
      console.error("No payment ID");
      return { statusCode: 200, body: "OK" };
    }

    // ── Dedup check 1: in-memory (same instance) ──
    if (processed.has(paymentId)) {
      console.log("Duplicate (in-memory), skipping:", paymentId);
      return { statusCode: 200, body: "OK" };
    }

    const MOLLIE_API_KEY = process.env.MOLLIE_API_KEY;
    const mollieRes = await fetch(`https://api.mollie.com/v2/payments/${paymentId}`, {
      headers: { Authorization: `Bearer ${MOLLIE_API_KEY}` },
    });
    const payment = await mollieRes.json();

    console.log("Payment status:", payment.status);
    if (payment.status !== "paid") return { statusCode: 200, body: "OK" };

    // ── Dedup check 2: timing-based (Mollie retries come after 15s+) ──
    // If payment was paid more than 25 seconds ago, this is a Mollie retry
    const paidAt = payment.paidAt ? new Date(payment.paidAt).getTime() : null;
    const now = Date.now();
    if (paidAt && (now - paidAt) > 25000) {
      console.log("Payment older than 25s — likely a Mollie retry, skipping:", paymentId);
      return { statusCode: 200, body: "OK" };
    }

    // Mark as processed BEFORE doing any work
    processed.add(paymentId);
    console.log("Processing payment:", paymentId);

    const meta = payment.metadata || {};
    const email = meta.email;
    const reportType = meta.reportType || "lab";
    const teaser = meta.teaser || "";
    const isLab = reportType === "lab";

    if (!email) {
      console.error("No email in metadata");
      return { statusCode: 200, body: "OK" };
    }

    const RESEND_API_KEY = process.env.RESEND_API_KEY;
    const ANTHROPIC_API_KEY = process.env.ANTHROPIC_API_KEY;

    // Step 1: Send immediate thank you email
    console.log("Sending thank you email to:", email);
    await fetch("https://api.resend.com/emails", {
      method: "POST",
      headers: { Authorization: `Bearer ${RESEND_API_KEY}`, "Content-Type": "application/json" },
      body: JSON.stringify({
        from: "HealthDecoded <onboarding@resend.dev>",
        to: email,
        subject: "✅ Payment confirmed — Your report is being generated",
        html: `
          <div style="font-family:Arial,sans-serif;max-width:600px;margin:0 auto;padding:32px;color:#1e293b;">
            <div style="text-align:center;margin-bottom:32px;">
              <h1 style="color:#0ea5e9;font-size:28px;margin-bottom:8px;">Health<span style="color:#0f172a;">Decoded</span></h1>
            </div>
            <div style="background:#f0fdf4;border:2px solid #16a34a;border-radius:12px;padding:24px;margin-bottom:24px;text-align:center;">
              <div style="font-size:48px;margin-bottom:12px;">✅</div>
              <h2 style="color:#16a34a;font-size:22px;margin-bottom:8px;">Payment confirmed!</h2>
              <p style="color:#166534;font-size:15px;">Thank you! Your full health report is now being generated by our AI.</p>
            </div>
            <div style="background:#f0f9ff;border:1px solid #bae6fd;border-radius:10px;padding:20px;margin-bottom:24px;">
              <h3 style="color:#0369a1;margin-bottom:12px;">⏱️ What happens next?</h3>
              <p style="color:#374151;font-size:14px;line-height:1.7;">
                Our AI is now generating your complete ${isLab ? "blood test analysis" : "health consultation"} report.
                You will receive a <strong>second email</strong> with your full report within the next few minutes.
              </p>
              <p style="color:#64748b;font-size:13px;margin-top:12px;">📧 Check your spam folder if you don't see it within 10 minutes.</p>
            </div>
            <div style="text-align:center;padding:16px;background:#f8fafc;border-radius:8px;">
              <p style="color:#64748b;font-size:12px;margin:0;">HealthDecoded · Educational content only · Not a medical device<br/>Always consult a qualified healthcare professional</p>
            </div>
          </div>
        `,
      }),
    });
    console.log("Thank you email sent");

    // Step 2: Generate full report with Claude
    console.log("Generating report with Claude...");
    const prompt = isLab
      ? `You are an expert clinical lab results interpreter. A patient paid for a blood test analysis report. Their blood test preview: "${teaser}"

Based on this preview, generate a detailed, personalised blood test analysis report. Be specific and clinically precise. Return ONLY valid JSON, no markdown:

{"labSummary":"Write 2-3 sentences summarising the overall blood health picture based on the preview","overallScore":72,"biomarkers":[{"name":"Write the specific biomarker name from the preview","value":"Write the specific value mentioned","referenceRange":"Write the lab reference range","optimalRange":"Write the optimal functional range","status":"optimal|normal|borderline|concerning|critical","category":"Metabolic|Thyroid|Blood Count|Lipids|Vitamins|Inflammation|Hormones|Liver|Kidney","interpretation":"Write a full paragraph explaining what this biomarker measures, what this specific value means for the patient, health implications, causes of high or low values, and what to watch for. Be specific and educational."},{"name":"Add more biomarkers from the preview as needed","value":"","referenceRange":"","optimalRange":"","status":"normal","category":"Blood Count","interpretation":""}],"keyFindings":["Write 3-5 specific key findings from the blood test preview","Each finding should be specific and actionable","Mention actual values where known from the preview"],"recommendedTests":["List additional tests worth considering based on the findings","Be specific about what each test would reveal"],"doctorTalkingPoints":["Write 3-5 specific questions to ask the doctor based on these results","Make them precise and relevant to the actual findings"],"retestPlan":{"timeframe":"6-8 weeks","reason":"Write specific reason based on the findings","markersToRetest":["List the specific markers most important to recheck"],"expectedImprovements":"Write what improvements are expected with the right interventions"}}`
      : `You are an AI health consultant. A patient paid for a health consultation report. Their case summary: "${teaser}"

Based on this, generate a personalised health consultation report. Return ONLY valid JSON with no markdown, no explanation, just the JSON object:

{"urgency":{"level":2,"label":"Book appointment within 2-4 weeks","color":"yellow","message":"Write a personalised urgency message based on the case summary","showActions":true},"summary":"Write 2-3 sentences summarising the key health patterns from the case summary","healthScore":{"metabolic":65,"weight":70,"sleep":60,"overall":65},"actionCards":[{"finding":"Main Health Concern","severity":"borderline","explanation":"Write a specific explanation based on the case summary","actions":[{"type":"lifestyle","title":"Sleep optimisation","detail":"Go to bed and wake at the same time daily. Poor sleep amplifies most symptoms."},{"type":"diet","title":"Anti-inflammatory nutrition","detail":"Reduce processed foods, increase omega-3 rich foods and colourful vegetables."},{"type":"doctor","title":"Book a comprehensive check-up","detail":"Request a full blood panel including CBC, thyroid, vitamin D, B12, ferritin, glucose and CRP."}],"retestIn":"6-8 weeks"}],"concerns":[{"name":"Nutritional deficiencies","confidence":"Medium","reasoning":"Common pattern in cases like this — vitamin D, iron, B12 or magnesium worth checking."},{"name":"Stress response","confidence":"Medium","reasoning":"Symptoms may reflect prolonged stress affecting multiple body systems."}],"suggestedTests":[{"test":"Full blood count (CBC)","reason":"Baseline for all blood cell levels"},{"test":"Thyroid panel (TSH, Free T4)","reason":"Affects energy, weight and mood"},{"test":"Vitamin D","reason":"Deficiency extremely common"},{"test":"Ferritin","reason":"Low ferritin causes fatigue even without anaemia"},{"test":"HbA1c","reason":"Blood sugar regulation"},{"test":"CRP","reason":"Silent inflammation marker"}],"doctorQuestions":["Could my symptoms relate to a nutritional deficiency?","Would you recommend a full blood panel?","Are there lifestyle changes you would prioritise?","Should I see a specialist for any of these symptoms?"],"homeEssentials":[{"item":"Vitamin D3 + K2","reason":"Impacts energy, immunity and mood"},{"item":"Magnesium glycinate","reason":"Supports sleep and stress response"},{"item":"Omega-3 fish oil","reason":"Anti-inflammatory, supports brain and heart"}]}`;

    const claudeRes = await fetch("https://api.anthropic.com/v1/messages", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "x-api-key": ANTHROPIC_API_KEY,
        "anthropic-version": "2023-06-01",
      },
      body: JSON.stringify({
        model: "claude-sonnet-4-6",
        max_tokens: 1500,
        messages: [{ role: "user", content: prompt }],
      }),
    });

    const claudeData = await claudeRes.json();
    const reportText = claudeData.content.map((c) => c.text || "").join("");
    let report = null;
    try {
      report = JSON.parse(reportText.replace(/```json|```/g, "").trim());
      console.log("Report generated successfully");
    } catch(e) {
      console.error("Failed to parse Claude response:", e.message);
    }

    // Build email HTML
    let reportHtml = "";

    if (report && isLab && report.labSummary) {
      const statusColors = {
        optimal: { bg: "#dcfce7", color: "#16a34a", label: "Optimal" },
        normal: { bg: "#dbeafe", color: "#1d4ed8", label: "Normal" },
        borderline: { bg: "#fef9c3", color: "#ca8a04", label: "Borderline" },
        concerning: { bg: "#fff7ed", color: "#ea580c", label: "Concerning" },
        critical: { bg: "#fee2e2", color: "#dc2626", label: "Critical" },
      };
      const scoreCol = report.overallScore >= 70 ? "#16a34a" : report.overallScore >= 50 ? "#ca8a04" : "#dc2626";
      const scoreBg = report.overallScore >= 70 ? "#dcfce7" : report.overallScore >= 50 ? "#fef9c3" : "#fee2e2";
      const categories = [...new Set((report.biomarkers || []).map((b) => b.category))];

      let biomarkersHtml = "";
      categories.forEach((cat) => {
        biomarkersHtml += `<h3 style="color:#7c3aed;font-size:15px;margin:20px 0 10px;border-bottom:2px solid #e2e8f0;padding-bottom:6px;">${cat}</h3>`;
        report.biomarkers.filter((b) => b.category === cat).forEach((b) => {
          const sc = statusColors[b.status] || statusColors.normal;
          biomarkersHtml += `
            <div style="border-radius:8px;border:1px solid #e2e8f0;margin-bottom:10px;overflow:hidden;">
              <div style="background:${sc.bg};padding:10px 14px;">
                <strong style="font-size:14px;color:#0f172a;">${b.name}</strong>
                <span style="font-size:12px;color:#64748b;margin-left:8px;">
                  ${b.value ? `Value: <strong style="color:${sc.color};">${b.value}</strong>` : ""}
                  ${b.referenceRange ? ` · Ref: ${b.referenceRange}` : ""}
                  ${b.optimalRange ? ` · Optimal: ${b.optimalRange}` : ""}
                </span>
                <span style="float:right;background:#fff;color:${sc.color};font-size:11px;font-weight:700;padding:2px 8px;border-radius:8px;">${sc.label}</span>
              </div>
              <div style="padding:10px 14px;font-size:13px;color:#374151;line-height:1.6;">${b.interpretation}</div>
            </div>`;
        });
      });

      reportHtml = `
        <div style="background:${scoreBg};border:2px solid ${scoreCol};border-radius:12px;padding:20px;margin-bottom:20px;">
          <div style="display:flex;align-items:center;gap:16px;">
            <div style="width:60px;height:60px;border-radius:50%;background:#fff;border:3px solid ${scoreCol};display:flex;align-items:center;justify-content:center;font-size:20px;font-weight:800;color:${scoreCol};flex-shrink:0;">${report.overallScore}</div>
            <div>
              <div style="font-weight:700;font-size:15px;color:#0f172a;margin-bottom:6px;">Overall Health Score</div>
              <div style="font-size:13px;color:#374151;line-height:1.6;">${report.labSummary}</div>
            </div>
          </div>
        </div>
        ${report.keyFindings?.length ? `
          <h2 style="color:#0369a1;font-size:16px;margin:24px 0 10px;border-bottom:2px solid #e2e8f0;padding-bottom:6px;">🎯 Key Findings</h2>
          ${report.keyFindings.map((f, i) => `<div style="margin-bottom:8px;padding:8px 12px;background:#f0f9ff;border-left:3px solid #0ea5e9;border-radius:4px;font-size:13px;">${i + 1}. ${f}</div>`).join("")}` : ""}
        <h2 style="color:#7c3aed;font-size:16px;margin:24px 0 10px;border-bottom:2px solid #e2e8f0;padding-bottom:6px;">🔬 Biomarker Analysis</h2>
        ${biomarkersHtml}
        ${report.retestPlan ? `
          <h2 style="color:#ca8a04;font-size:16px;margin:24px 0 10px;border-bottom:2px solid #e2e8f0;padding-bottom:6px;">🔁 When to Retest</h2>
          <div style="background:#fffbeb;border:1px solid #fde68a;border-radius:8px;padding:14px;">
            <div style="font-size:16px;font-weight:800;color:#ca8a04;margin-bottom:6px;">Recommended: ${report.retestPlan.timeframe}</div>
            <div style="font-size:13px;margin-bottom:8px;">${report.retestPlan.reason}</div>
            <div style="font-size:13px;"><strong>Expected improvements:</strong> ${report.retestPlan.expectedImprovements}</div>
            ${report.retestPlan.markersToRetest?.length ? `<div style="margin-top:10px;">${report.retestPlan.markersToRetest.map(m => `<span style="display:inline-block;font-size:11px;background:#fff;color:#92400e;padding:3px 10px;border-radius:8px;border:1px solid #fde68a;margin:3px;">${m}</span>`).join("")}</div>` : ""}
          </div>` : ""}
        ${report.doctorTalkingPoints?.length ? `
          <h2 style="color:#0369a1;font-size:16px;margin:24px 0 10px;border-bottom:2px solid #e2e8f0;padding-bottom:6px;">💬 What to Discuss with Your Doctor</h2>
          ${report.doctorTalkingPoints.map(q => `<div style="font-size:13px;padding:8px 12px;background:#f0f9ff;border-radius:5px;border-left:3px solid #0ea5e9;margin-bottom:6px;">${q}</div>`).join("")}` : ""}
        ${report.recommendedTests?.length ? `
          <h2 style="color:#7c3aed;font-size:16px;margin:24px 0 10px;border-bottom:2px solid #e2e8f0;padding-bottom:6px;">🔬 Recommended Tests</h2>
          ${report.recommendedTests.map(t => `<div style="font-size:13px;margin-bottom:6px;">→ ${t}</div>`).join("")}` : ""}
      `;
    } else if (report && !isLab) {
      const urgColors = { green: { bg:"#dcfce7", border:"#16a34a", text:"#14532d" }, yellow: { bg:"#fef9c3", border:"#ca8a04", text:"#713f12" }, orange: { bg:"#fff7ed", border:"#ea580c", text:"#7c2d12" }, red: { bg:"#fee2e2", border:"#dc2626", text:"#7f1d1d" } };
      const uc = urgColors[report.urgency?.color] || urgColors.green;
      reportHtml = `
        <div style="background:${uc.bg};border:2px solid ${uc.border};border-radius:12px;padding:16px;margin-bottom:20px;">
          <div style="font-size:17px;font-weight:800;color:${uc.text};">Urgency Level ${report.urgency?.level}/5 — ${report.urgency?.label}</div>
          <div style="font-size:13px;color:${uc.text};line-height:1.6;margin-top:8px;">${report.urgency?.message}</div>
        </div>
        ${report.summary ? `<div style="background:#f0f9ff;border:1px solid #bae6fd;border-radius:10px;padding:14px;margin-bottom:16px;font-size:14px;color:#0369a1;line-height:1.6;">${report.summary}</div>` : ""}
        ${report.actionCards?.length ? `
          <h2 style="color:#0f172a;font-size:16px;margin:24px 0 10px;">🎯 Action Plan</h2>
          ${report.actionCards.map(card => `
            <div style="border:1px solid #e2e8f0;border-radius:10px;margin-bottom:12px;overflow:hidden;">
              <div style="background:#f8fafc;padding:10px 14px;font-weight:700;font-size:14px;">${card.finding}</div>
              <div style="padding:10px 14px;font-size:13px;color:#374151;">${card.explanation}</div>
              ${card.actions?.map(a => `<div style="margin:0 14px 10px;background:#f0f9ff;border-radius:8px;padding:10px;"><div style="font-weight:700;font-size:13px;color:#0369a1;">${a.title}</div><div style="font-size:13px;">${a.detail}</div></div>`).join("") || ""}
            </div>`).join("")}` : ""}
        ${report.doctorQuestions?.length ? `
          <h2 style="color:#0369a1;font-size:16px;margin:24px 0 10px;">💬 Questions for Your Doctor</h2>
          ${report.doctorQuestions.map(q => `<div style="font-size:13px;padding:8px 12px;background:#f0f9ff;border-radius:5px;border-left:3px solid #0ea5e9;margin-bottom:6px;">${q}</div>`).join("")}` : ""}
        ${report.suggestedTests?.length ? `
          <h2 style="color:#7c3aed;font-size:16px;margin:24px 0 10px;">🔬 Suggested Tests</h2>
          ${report.suggestedTests.map(t => `<div style="font-size:13px;margin-bottom:6px;">→ <strong>${t.test}</strong> — ${t.reason}</div>`).join("")}` : ""}
        ${report.homeEssentials?.length ? `
          <h2 style="color:#16a34a;font-size:16px;margin:24px 0 10px;">🏠 Home Essentials</h2>
          ${report.homeEssentials.map(h => `<div style="font-size:13px;padding:8px 12px;background:#f0fdf4;border-radius:5px;border-left:3px solid #16a34a;margin-bottom:6px;"><strong>${h.item}</strong> — ${h.reason}</div>`).join("")}` : ""}
      `;
    } else {
      reportHtml = `<div style="background:#fff7ed;border:1px solid #fed7aa;border-radius:10px;padding:20px;font-size:14px;color:#9a3412;">
        We encountered an issue generating your report. Please contact us and we will send your report manually within 24 hours.
      </div>`;
    }

    // Send full report email
    await fetch("https://api.resend.com/emails", {
      method: "POST",
      headers: { Authorization: `Bearer ${RESEND_API_KEY}`, "Content-Type": "application/json" },
      body: JSON.stringify({
        from: "HealthDecoded <onboarding@resend.dev>",
        to: email,
        subject: `📊 Your HealthDecoded ${isLab ? "Blood Test Analysis" : "Health Consultation"} Report`,
        html: `
          <div style="font-family:Arial,sans-serif;max-width:700px;margin:0 auto;padding:32px;color:#1e293b;">
            <div style="text-align:center;margin-bottom:32px;">
              <h1 style="color:#0ea5e9;font-size:28px;margin-bottom:8px;">Health<span style="color:#0f172a;">Decoded</span></h1>
              <p style="color:#64748b;font-size:14px;">AI-powered health analysis — educational content only</p>
            </div>
            <div style="background:#fffbeb;border:1px solid #fde68a;border-radius:8px;padding:12px 16px;margin-bottom:24px;font-size:12px;color:#92400e;">
              <strong>Important:</strong> This report is AI-generated for educational purposes only. Not a medical diagnosis. Always consult a qualified healthcare professional.
            </div>
            <h2 style="color:#0f172a;font-size:20px;margin-bottom:20px;">Your ${isLab ? "Blood Test Analysis" : "Health Consultation"} Report</h2>
            ${reportHtml}
            <div style="margin-top:32px;padding:16px;background:#f1f5f9;border-radius:8px;font-size:11px;color:#64748b;text-align:center;">
              HealthDecoded · AI-generated educational content only · Not a medical device<br/>Always consult a qualified healthcare professional
            </div>
          </div>
        `,
      }),
    });

    console.log("Full report email sent to:", email);
    return { statusCode: 200, body: "OK" };

  } catch (err) {
    console.error("payment-webhook error:", err);
    return { statusCode: 200, body: "OK" };
  }
}
