// In-memory dedup — works within same instance
const processed = new Set();

export async function handler(event) {
  console.log("payment-webhook triggered");

  try {
    const params = new URLSearchParams(event.body);
    const paymentId = params.get("id");

    if (!paymentId) {
      console.error("No payment ID");
      return { statusCode: 200, body: "OK" };
    }

    // ── Dedup check: in-memory (same instance) ──
    if (processed.has(paymentId)) {
      console.log("Duplicate (in-memory), skipping:", paymentId);
      return { statusCode: 200, body: "OK" };
    }

    const MOLLIE_API_KEY = process.env.MOLLIE_API_KEY;
    const mollieRes = await fetch(`https://api.mollie.com/v2/payments/${paymentId}`, {
      headers: { Authorization: `Bearer ${MOLLIE_API_KEY}` },
    });
    const payment = await mollieRes.json();

    console.log("Payment status:", payment.status);
    if (payment.status !== "paid") return { statusCode: 200, body: "OK" };

    // ── Timing check: block Mollie retries (arrive 60s+ after payment) ──
    const paidAt = payment.paidAt ? new Date(payment.paidAt).getTime() : null;
    const now = Date.now();
    if (paidAt && (now - paidAt) > 90000) {
      console.log("Payment older than 90s — Mollie retry, skipping:", paymentId);
      return { statusCode: 200, body: "OK" };
    }

    // Mark as processed BEFORE doing any work
    processed.add(paymentId);
    console.log("Processing payment:", paymentId);

    const meta = payment.metadata || {};
    const email = meta.email;
    const reportType = meta.reportType || "lab";
    const teaser = meta.teaser || "";
    const isLab = reportType === "lab";

    if (!email) {
      console.error("No email in metadata");
      return { statusCode: 200, body: "OK" };
    }

    const RESEND_API_KEY = process.env.RESEND_API_KEY;
    const ANTHROPIC_API_KEY = process.env.ANTHROPIC_API_KEY;

    // Step 1: Send immediate confirmation email
    console.log("Sending confirmation email to:", email);
    await fetch("https://api.resend.com/emails", {
      method: "POST",
      headers: { Authorization: `Bearer ${RESEND_API_KEY}`, "Content-Type": "application/json" },
      body: JSON.stringify({
        from: "HealthDecoded <onboarding@resend.dev>",
        to: email,
        subject: "✅ Payment confirmed — Your report is being generated",
        html: `
          <div style="font-family:Arial,sans-serif;max-width:600px;margin:0 auto;padding:32px;color:#1e293b;">
            <div style="text-align:center;margin-bottom:32px;">
              <h1 style="color:#0ea5e9;font-size:28px;margin-bottom:8px;">Health<span style="color:#0f172a;">Decoded</span></h1>
            </div>
            <div style="background:#f0fdf4;border:2px solid #16a34a;border-radius:12px;padding:24px;margin-bottom:24px;text-align:center;">
              <div style="font-size:48px;margin-bottom:12px;">✅</div>
              <h2 style="color:#16a34a;font-size:22px;margin-bottom:8px;">Payment confirmed!</h2>
              <p style="color:#166534;font-size:15px;">Thank you! Your full health report is now being generated by our AI.</p>
            </div>
            <div style="background:#f0f9ff;border:1px solid #bae6fd;border-radius:10px;padding:20px;margin-bottom:24px;">
              <h3 style="color:#0369a1;margin-bottom:12px;">⏱️ What happens next?</h3>
              <p style="color:#374151;font-size:14px;line-height:1.7;">
                Our AI is now generating your complete ${isLab ? "blood test analysis" : "health consultation"} report.
                You will receive a <strong>second email</strong> with your full report within the next few minutes.
              </p>
              <p style="color:#64748b;font-size:13px;margin-top:12px;">📧 Check your spam folder if you don't see it within 10 minutes.</p>
            </div>
            <div style="text-align:center;padding:16px;background:#f8fafc;border-radius:8px;">
              <p style="color:#64748b;font-size:12px;margin:0;">HealthDecoded · Educational content only · Not a medical device<br/>Always consult a qualified healthcare professional</p>
            </div>
          </div>
        `,
      }),
    });
    console.log("Confirmation email sent");

    // Step 2: Generate report HTML directly with Claude
    console.log("Generating report with Claude...");

    const prompt = isLab
      ? `You are an expert clinical lab results interpreter. A patient paid for a blood test analysis. Their blood test preview: "${teaser}"

Write a complete personalised blood test analysis report as HTML with inline styles. Be specific and use the actual values from the preview. Return ONLY the HTML content (no explanation, no markdown):

<div style="font-family:Arial,sans-serif;color:#1e293b;">

<div style="background:#f0f9ff;border:2px solid #0369a1;border-radius:12px;padding:20px;margin-bottom:20px;">
<h2 style="color:#0369a1;margin:0 0 10px;">Overall Score: [X]/100</h2>
<p style="margin:0;font-size:14px;line-height:1.7;">[Write 2-3 sentences summarising the overall blood health picture]</p>
</div>

<h2 style="color:#0369a1;font-size:16px;border-bottom:2px solid #e2e8f0;padding-bottom:6px;">🎯 Key Findings</h2>
[For each key finding: <div style="margin-bottom:8px;padding:8px 12px;background:#f0f9ff;border-left:3px solid #0ea5e9;border-radius:4px;font-size:13px;">[finding]</div>]

<h2 style="color:#7c3aed;font-size:16px;border-bottom:2px solid #e2e8f0;padding-bottom:6px;margin-top:24px;">🔬 Biomarker Analysis</h2>
[For each biomarker: <div style="border-radius:8px;border:1px solid #e2e8f0;margin-bottom:12px;overflow:hidden;"><div style="background:[#dcfce7 optimal/#dbeafe normal/#fef9c3 borderline/#fff7ed concerning/#fee2e2 critical];padding:10px 14px;"><strong>[Name]</strong> <span style="font-size:12px;color:#64748b;margin-left:8px;">Value: <strong>[value]</strong> · Ref: [ref range] · Optimal: [optimal range]</span><span style="float:right;font-size:11px;font-weight:700;padding:2px 8px;border-radius:8px;background:#fff;color:[status color];">[Status]</span></div><div style="padding:12px 14px;font-size:13px;line-height:1.6;">[Full interpretation paragraph]</div></div>]

<h2 style="color:#ca8a04;font-size:16px;border-bottom:2px solid #e2e8f0;padding-bottom:6px;margin-top:24px;">🔁 When to Retest</h2>
<div style="background:#fffbeb;border:1px solid #fde68a;border-radius:8px;padding:14px;"><div style="font-size:16px;font-weight:800;color:#ca8a04;margin-bottom:6px;">[Timeframe]</div><p style="font-size:13px;margin:0 0 8px;">[Reason]</p><p style="font-size:13px;margin:0;"><strong>Priority markers:</strong> [markers]</p></div>

<h2 style="color:#0369a1;font-size:16px;border-bottom:2px solid #e2e8f0;padding-bottom:6px;margin-top:24px;">💬 What to Discuss with Your Doctor</h2>
[Each question: <div style="font-size:13px;padding:8px 12px;background:#f0f9ff;border-radius:5px;border-left:3px solid #0ea5e9;margin-bottom:6px;">[question]</div>]

<h2 style="color:#7c3aed;font-size:16px;border-bottom:2px solid #e2e8f0;padding-bottom:6px;margin-top:24px;">🔬 Recommended Tests</h2>
[Each: <div style="font-size:13px;margin-bottom:6px;">→ [test and reason]</div>]

</div>`

      : `You are an AI health consultant. A patient paid for a health consultation. Their case summary: "${teaser}"

Write a complete personalised health consultation report as HTML with inline styles. Reference the actual symptoms. Return ONLY the HTML content (no explanation, no markdown):

<div style="font-family:Arial,sans-serif;color:#1e293b;">

<div style="background:#fef9c3;border:2px solid #ca8a04;border-radius:12px;padding:16px;margin-bottom:20px;">
<div style="font-size:17px;font-weight:800;color:#713f12;">Urgency Level [X]/5 — [Label]</div>
<p style="font-size:13px;color:#713f12;line-height:1.6;margin-top:8px;">[Personalised urgency message]</p>
</div>

<div style="background:#f0f9ff;border:1px solid #bae6fd;border-radius:10px;padding:14px;margin-bottom:16px;font-size:14px;color:#0369a1;line-height:1.6;">[Overall summary 2-3 sentences]</div>

<h2 style="color:#0f172a;font-size:16px;margin:24px 0 10px;">🎯 Action Plan</h2>
[For each action area: <div style="border:1px solid #e2e8f0;border-radius:10px;margin-bottom:12px;overflow:hidden;"><div style="background:#f8fafc;padding:10px 14px;font-weight:700;font-size:14px;">[Area]</div><div style="padding:10px 14px;font-size:13px;color:#374151;line-height:1.6;">[Explanation]</div><div style="margin:0 14px 12px;background:#f0f9ff;border-radius:8px;padding:10px;"><div style="font-weight:700;font-size:13px;color:#0369a1;margin-bottom:4px;">[Action]</div><div style="font-size:13px;line-height:1.6;">[Detail]</div></div></div>]

<h2 style="color:#0369a1;font-size:16px;margin:24px 0 10px;">💬 Questions for Your Doctor</h2>
[Each: <div style="font-size:13px;padding:8px 12px;background:#f0f9ff;border-radius:5px;border-left:3px solid #0ea5e9;margin-bottom:6px;">[question]</div>]

<h2 style="color:#7c3aed;font-size:16px;margin:24px 0 10px;">🔬 Suggested Tests</h2>
[Each: <div style="font-size:13px;margin-bottom:6px;">→ <strong>[test]</strong> — [reason]</div>]

<h2 style="color:#16a34a;font-size:16px;margin:24px 0 10px;">🏠 Home Essentials</h2>
[Each: <div style="font-size:13px;padding:8px 12px;background:#f0fdf4;border-radius:5px;border-left:3px solid #16a34a;margin-bottom:6px;"><strong>[item]</strong> — [reason]</div>]

</div>`;

    const claudeRes = await fetch("https://api.anthropic.com/v1/messages", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "x-api-key": ANTHROPIC_API_KEY,
        "anthropic-version": "2023-06-01",
      },
      body: JSON.stringify({
        model: "claude-sonnet-4-6",
        max_tokens: 2500,
        messages: [{ role: "user", content: prompt }],
      }),
    });

    const claudeData = await claudeRes.json();
    const reportHtml = claudeData.content.map((c) => c.text || "").join("").replace(/^```html\n?/, "").replace(/```$/, "").trim();
    console.log("Report generated, length:", reportHtml.length);

    const fallbackHtml = `<div style="background:#fff7ed;border:1px solid #fed7aa;border-radius:10px;padding:20px;font-size:14px;color:#9a3412;">
      We encountered an issue generating your report. Please contact us and we will send your report manually within 24 hours.
    </div>`;

    // Send full report email
    await fetch("https://api.resend.com/emails", {
      method: "POST",
      headers: { Authorization: `Bearer ${RESEND_API_KEY}`, "Content-Type": "application/json" },
      body: JSON.stringify({
        from: "HealthDecoded <onboarding@resend.dev>",
        to: email,
        subject: `📊 Your HealthDecoded ${isLab ? "Blood Test Analysis" : "Health Consultation"} Report`,
        html: `
          <div style="font-family:Arial,sans-serif;max-width:700px;margin:0 auto;padding:32px;color:#1e293b;">
            <div style="text-align:center;margin-bottom:32px;">
              <h1 style="color:#0ea5e9;font-size:28px;margin-bottom:8px;">Health<span style="color:#0f172a;">Decoded</span></h1>
              <p style="color:#64748b;font-size:14px;">AI-powered health analysis — educational content only</p>
            </div>
            <div style="background:#fffbeb;border:1px solid #fde68a;border-radius:8px;padding:12px 16px;margin-bottom:24px;font-size:12px;color:#92400e;">
              <strong>Important:</strong> This report is AI-generated for educational purposes only. Not a medical diagnosis. Always consult a qualified healthcare professional.
            </div>
            <h2 style="color:#0f172a;font-size:20px;margin-bottom:20px;">Your ${isLab ? "Blood Test Analysis" : "Health Consultation"} Report</h2>
            ${reportHtml.length > 100 ? reportHtml : fallbackHtml}
            <div style="margin-top:32px;padding:16px;background:#f1f5f9;border-radius:8px;font-size:11px;color:#64748b;text-align:center;">
              HealthDecoded · AI-generated educational content only · Not a medical device<br/>Always consult a qualified healthcare professional
            </div>
          </div>
        `,
      }),
    });

    console.log("Full report email sent to:", email);
    return { statusCode: 200, body: "OK" };

  } catch (err) {
    console.error("payment-webhook error:", err);
    return { statusCode: 200, body: "OK" };
  }
}
